
# application-dev.properties
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Correct dialect for MySQL 8+
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/shrunity
management.info.env.enabled=true

# Info endpoint data
info.app.name=E-Commerce App
info.app.version=1.0.0
info.app.developer=Shrunity IT


